# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b81f8a9b5b9ba1cb122b80a6247afa2e2a1a1293f71f9acc341e24e015b83882c9f87097ea23cad6fb5cb34a58daba94a53c0a84f4b638347da0403197a02c1

test:
  secret_key_base: 9b6a51a18daa26bf72545ec61135ae0e9b69fab6b336e16f81eacf57cc4591aa140a91e4368cc9cdf651e1680da1343dd39b5e843e31b4ff7d0da25a3a24e0b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
